-- ===========================================================================
--  070_charges_payments_and_what_a_family_owes.sql
--  20 September 2026
--
--  THE LEDGER. Two tables: what was charged, and what came in.
--
--  ---------------------------------------------------------------------------
--  THE ONE DECISION THAT SHAPES EVERY SCREEN: NO ALLOCATION TABLE
--  ---------------------------------------------------------------------------
--
--  The textbook design has a third table joining payments to charges, so the
--  system can say which term a particular £40 paid off. This one does not
--  have it, and that is a decision rather than an omission.
--
--  Allocation answers a question nobody at a masjid asks, and asks one nobody
--  can answer. A father transfers £100 for three children across two terms
--  with an outstanding balance from last year. Which charge did it pay? There
--  is no true answer — he paid a hundred pounds off what he owed. Force the
--  office to pick one and you get a screen where somebody has to guess, and
--  guesses get recorded as facts. Then a sibling discount is applied
--  retrospectively, the charge it was allocated against shrinks, and the
--  allocation is wrong in a way that shows up as a term marked paid that
--  isn't.
--
--  So: A FAMILY HAS A BALANCE. Everything charged, minus everything received.
--  One number, always true, never needing a judgement call. "Outstanding"
--  means that number is above zero. A refund is a payment with a minus sign,
--  so the same subtraction covers it and there is no second code path that
--  could disagree with the first.
--
--  The cost is real and worth naming: this system cannot tell you that the
--  Autumn term specifically is unpaid. It can tell you the family owes £86
--  and show every charge and every payment that makes up the figure, which is
--  what a parent ringing the office actually wants read out to them.
--
--  ---------------------------------------------------------------------------
--  MONEY ARRIVING BY CARD IS RECORDED BY A PERSON, NOT BY A WEBHOOK
--  ---------------------------------------------------------------------------
--
--  The hall deposit and the nikah fee post themselves: Stripe calls the
--  webhook, the reference in the payment carries HH- or NK-, and the right
--  booking is marked paid. Madrasah fees deliberately do not do this.
--
--  Those references are generated by this system and shown to one person for
--  one payment. A madrasah fee reference is given to a parent in September
--  and typed by them, from memory, into a banking app, monthly, for a year.
--  It will be typed wrong. Auto-posting means a payment credited to the wrong
--  family — and the family who actually paid keeps getting reminders while
--  somebody else's balance quietly clears. That is a worse failure than
--  typing it in by hand, and it is silent.
--
--  So every receipt, whatever route it came by, is entered on the Bank
--  transfers screen by somebody who looked at it. One place where money is
--  recorded, which is also what stops this becoming the two-lists problem
--  this project spent a day removing.
--
--  Prerequisites: 068 (families), 069 (rates and terms). APPLY 068-071 AS A
--  SET, in order. Three functions here and in 069 reach forwards — 069's
--  madrasah_fee_structure() reads the charges table this file creates, and
--  madrasah_fee_balances() below reads the reminder log 071 creates. plpgsql
--  does not resolve a table until the function runs, so each file applies
--  cleanly on its own and then fails at the first press of a button. The
--  reminder log the balances function reads now lives in THIS file for that
--  reason, defined where it is first used. 069's forward reference to the
--  charges table is left alone, because 069 and 070 are never useful apart
--  and a guard would be a second thing to keep right.
--  Idempotent.
-- ===========================================================================

begin;

-- ---------------------------------------------------------------------------
--  1. What was charged
--
--  household_id is NOT NULL. A charge with no family cannot be billed, cannot
--  be collected and cannot appear on a statement — it is a number in a table.
--  The generator skips pupils who have no family yet and REPORTS how many,
--  which is the honest behaviour: on the day this goes live, 543 imported
--  children have no household at all.
--
--  pupil_id is nullable, because some charges are against the family rather
--  than a child (a one-off correction, a balance brought forward from the old
--  system). ON DELETE SET NULL, never CASCADE — 058's rule again. Deleting a
--  pupil three years after they leave must not delete the charity's financial
--  record of what was charged, which is on a six-year clock.
-- ---------------------------------------------------------------------------
create table if not exists public.madrasah_charges (
  id            uuid primary key default gen_random_uuid(),
  masjid_id     uuid not null references public.masjids(id) on delete cascade,
  household_id  uuid not null references public.madrasah_households(id) on delete restrict,
  pupil_id      uuid references public.madrasah_pupils(id) on delete set null,
  period_id     uuid references public.madrasah_fee_periods(id) on delete restrict,
  kind          text not null default 'tuition',
  description   text not null,
  weeks         numeric(4,1),
  rate_p        integer,
  gross_p       integer not null,
  discount_p    integer not null default 0,
  discount_note text,
  waived_p      integer not null default 0,
  waiver_note   text,
  --  GENERATED, not written. The one number every screen totals is computed
  --  by Postgres from the three it is made of, so a screen that forgets to
  --  subtract a waiver cannot produce a different answer from the report.
  net_p         integer generated always as (gross_p - discount_p - waived_p) stored,
  charged_on    date not null default current_date,
  created_at    timestamptz not null default now(),
  created_by    uuid,
  constraint madrasah_charge_has_a_description
    check (length(btrim(description)) between 1 and 160),
  constraint madrasah_charge_kind_valid
    check (kind in ('tuition', 'admission', 'other')),
  constraint madrasah_charge_gross_is_sane
    check (gross_p between 0 and 10000000),
  --  A DISCOUNT CANNOT EXCEED THE BILL. Without this, a mistyped waiver turns
  --  a charge negative, the family's balance goes into credit, and the
  --  Outstanding screen stops showing them — the error hides itself.
  constraint madrasah_charge_relief_within_bill
    check (discount_p >= 0 and waived_p >= 0 and discount_p + waived_p <= gross_p),
  constraint madrasah_charge_notes_are_short
    check ((discount_note is null or length(discount_note) <= 300)
       and (waiver_note   is null or length(waiver_note)   <= 300))
);

--  Re-running the generator for a term must not double-charge. This is the
--  thing that makes "Raise charges" safe to press twice, which somebody will.
create unique index if not exists madrasah_charge_one_per_pupil_per_term_idx
  on public.madrasah_charges (period_id, pupil_id)
  where period_id is not null and pupil_id is not null and kind = 'tuition';

create index if not exists madrasah_charge_household_idx
  on public.madrasah_charges (household_id, charged_on desc);

create index if not exists madrasah_charge_period_idx
  on public.madrasah_charges (period_id);

alter table public.madrasah_charges enable row level security;
alter table public.madrasah_charges force row level security;
revoke all on public.madrasah_charges from anon, authenticated;

-- ---------------------------------------------------------------------------
--  2. What came in
--
--  A REFUND IS A PAYMENT WITH A MINUS SIGN. One table, one subtraction, one
--  answer. A separate refunds table would mean every balance in the system is
--  charges minus payments plus refunds, and the day somebody writes a report
--  that forgets the third term is the day the trustees are given a figure
--  that is wrong in the masjid's favour.
--
--  bank_reference is what was ACTUALLY on the statement, not what it should
--  have said. When a father types MF-O148 with a letter O, that is what gets
--  recorded, because in six months the only way to tie the row back to the
--  bank is the string the bank has.
-- ---------------------------------------------------------------------------
create table if not exists public.madrasah_payments (
  id             uuid primary key default gen_random_uuid(),
  masjid_id      uuid not null references public.masjids(id) on delete cascade,
  household_id   uuid not null references public.madrasah_households(id) on delete restrict,
  kind           text not null default 'payment',
  method         text not null,
  amount_p       integer not null,
  received_on    date not null default current_date,
  bank_reference text,
  note           text,
  recorded_by    uuid,
  created_at     timestamptz not null default now(),
  constraint madrasah_payment_kind_valid check (kind in ('payment', 'refund')),
  constraint madrasah_payment_method_valid check (method in ('bank', 'card', 'cash', 'other')),
  --  THE SIGN AND THE KIND HAVE TO AGREE, in the database and not only on the
  --  screen. A refund stored as a positive number would increase what the
  --  family had paid — the exact opposite of what happened.
  constraint madrasah_payment_sign_matches_kind
    check ((kind = 'payment' and amount_p > 0) or (kind = 'refund' and amount_p < 0)),
  constraint madrasah_payment_is_sane check (abs(amount_p) <= 10000000),
  constraint madrasah_payment_note_is_short
    check ((note is null or length(note) <= 300)
       and (bank_reference is null or length(bank_reference) <= 60))
);

create index if not exists madrasah_payment_household_idx
  on public.madrasah_payments (household_id, received_on desc);

create index if not exists madrasah_payment_received_idx
  on public.madrasah_payments (masjid_id, received_on desc);

alter table public.madrasah_payments enable row level security;
alter table public.madrasah_payments force row level security;
revoke all on public.madrasah_payments from anon, authenticated;

-- ---------------------------------------------------------------------------
--  2b. The reminder log
--
--  It belongs with the reminders in 071 and it is here instead, because
--  madrasah_fee_balances() below reads it to say when a family was last
--  written to. Defined where it is first used.
--
--  WHAT IS LOGGED AND WHAT IS DELIBERATELY NOT: the family, the time and the
--  balance at the time — never the email address. The address is on the
--  guardian record and on the retention clock; copying it into a log that
--  outlives that record would quietly defeat the retention period. Same
--  reasoning the notify function already applies when it writes "office" or
--  "hirer" into an audit row instead of an address.
-- ---------------------------------------------------------------------------
create table if not exists public.madrasah_fee_reminders (
  id           uuid primary key default gen_random_uuid(),
  masjid_id    uuid not null references public.masjids(id) on delete cascade,
  household_id uuid not null references public.madrasah_households(id) on delete cascade,
  sent_at      timestamptz not null default now(),
  sent_by      uuid,
  balance_p    integer not null,
  outcome      text not null default 'sent',
  constraint madrasah_reminder_outcome_valid
    check (outcome in ('sent', 'failed', 'no_contact', 'too_soon', 'nothing_owed'))
);

create index if not exists madrasah_reminder_household_idx
  on public.madrasah_fee_reminders (household_id, sent_at desc);

alter table public.madrasah_fee_reminders enable row level security;
alter table public.madrasah_fee_reminders force row level security;
revoke all on public.madrasah_fee_reminders from anon, authenticated;

-- ---------------------------------------------------------------------------
--  3. Raising the charges for a term
--
--  One charge per pupil who is still here and has a family. Returns what it
--  did AND what it could not do, because "412 raised" on its own is a figure
--  that hides 131 children nobody is billing.
-- ---------------------------------------------------------------------------
create or replace function public.raise_madrasah_charges(p_period uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid  uuid := public.current_masjid();
  v_period  public.madrasah_fee_periods%rowtype;
  v_default integer;
  v_made    integer := 0;
  v_skipped integer := 0;
  v_already integer := 0;
  v_total   bigint := 0;
  v_p       record;
  v_gross   integer;
  v_disc    integer;
  v_rate    integer;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may raise charges.'
      using errcode = '42501';
  end if;

  select * into v_period from public.madrasah_fee_periods
   where id = p_period and masjid_id = v_masjid;
  if v_period.id is null then
    raise exception 'There is no such term at this masjid.' using errcode = 'no_data_found';
  end if;
  if v_period.status = 'closed' then
    raise exception 'That term is closed. Nothing more can be charged against it.'
      using errcode = 'check_violation';
  end if;

  select amount_p into v_default from public.madrasah_fee_rates
   where masjid_id = v_masjid and is_default and active;
  if v_default is null then
    raise exception 'No default rate is set, so there is nothing to charge most pupils. Set one on "What things cost" first.'
      using errcode = 'check_violation';
  end if;

  select count(*) into v_already from public.madrasah_charges
   where period_id = p_period and kind = 'tuition';

  for v_p in
    select p.id, p.household_id, p.first_name, p.last_name,
           coalesce(r.amount_p, v_default) as rate_p
      from public.madrasah_pupils p
      left join public.madrasah_fee_rates r
             on r.id = p.fee_rate_id and r.active
     where p.masjid_id = v_masjid
       and p.left_on is null
  loop
    if v_p.household_id is null then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    v_rate  := v_p.rate_p;
    --  Rounded once, here. weeks is numeric(4,1) and the rate is whole pence,
    --  so 13.5 weeks at £10 is 13500 exactly; a half-week at an odd rate is
    --  the case that needs the round, and doing it in one place means the
    --  charge and every report of it agree to the penny.
    v_gross := round(v_period.weeks * v_rate);
    v_disc  := public.madrasah_sibling_discount_p(v_p.household_id, v_p.id, v_gross);

    insert into public.madrasah_charges
      (masjid_id, household_id, pupil_id, period_id, kind, description,
       weeks, rate_p, gross_p, discount_p, discount_note, created_by)
    values (v_masjid, v_p.household_id, v_p.id, p_period, 'tuition',
            btrim(v_p.first_name || ' ' || coalesce(v_p.last_name, '')) || ' — ' || v_period.name,
            v_period.weeks, v_rate, v_gross, v_disc,
            case when v_disc > 0 then 'Sibling discount' else null end,
            auth.uid())
    on conflict (period_id, pupil_id) where period_id is not null
                                       and pupil_id is not null
                                       and kind = 'tuition'
    do nothing;

    if found then
      v_made  := v_made + 1;
      v_total := v_total + (v_gross - v_disc);
    end if;
  end loop;

  if v_made > 0 and v_period.status = 'draft' then
    update public.madrasah_fee_periods
       set status = 'issued', issued_at = coalesce(issued_at, now()), updated_at = now()
     where id = p_period;
  end if;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(), 'madrasah_charges_raised',
          jsonb_build_object('period', p_period, 'raised', v_made,
                             'skipped_no_family', v_skipped, 'total_p', v_total));

  return jsonb_build_object(
    'raised', v_made, 'skipped_no_family', v_skipped,
    'already_there', v_already, 'total_p', v_total,
    'period', v_period.name);
end $fn$;

-- ---------------------------------------------------------------------------
--  4. What every family owes
--
--  The single query the whole section rests on.
-- ---------------------------------------------------------------------------
create or replace function public.madrasah_fee_balances(
  p_only_owing boolean default false,
  p_q          text    default null)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_q      text := nullif(btrim(coalesce(p_q, '')), '');
  v_like   text;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may see what families owe.'
      using errcode = '42501';
  end if;

  v_like := case when v_q is null then null
                 else '%' || replace(replace(replace(v_q, '\', '\\'), '%', '\%'), '_', '\_') || '%' end;

  return coalesce((
    select jsonb_agg(x order by (x->>'balance_p')::bigint desc, x->>'name')
      from (
        select jsonb_build_object(
                 'id',          h.id,
                 'reference',   h.reference,
                 'name',        h.name,
                 'charged_p',   coalesce(c.total, 0),
                 'paid_p',      coalesce(y.total, 0),
                 'balance_p',   coalesce(c.total, 0) - coalesce(y.total, 0),
                 'last_paid_on', y.last_on,
                 'pupils',      (select count(*) from public.madrasah_pupils p
                                  where p.household_id = h.id and p.left_on is null),
                 --  Whether there is somebody to email, not their address.
                 --  065's rule: a list is read far more often than a record is
                 --  opened, and this one is downloaded to a spreadsheet.
                 --  THE PRIMARY CONTACT'S email, not any guardian's. The
                 --  sender writes to the primary and nobody else; a family
                 --  whose primary has only a telephone number and whose second
                 --  parent has an email was tickable here, survived the "only
                 --  families we can email" filter, and came back no_contact.
                 'can_email',   exists (select 1 from public.madrasah_guardians g
                                         where g.household_id = h.id
                                           and g.is_primary
                                           and g.email is not null),
                 --  THE SAME FILTER THE SENDER USES, AND NOTHING ELSE.
                 --
                 --  Every press of the reminder button logs a row for the
                 --  families it did NOT write to as well — no_contact,
                 --  too_soon, nothing_owed. Counting those as "last reminded"
                 --  made the screen say a family had been written to
                 --  yesterday when it had not, put them in the confirm
                 --  dialog's "will be skipped" count, and then email them
                 --  anyway.
                 --
                 --  'queued' joined the list at 072 and had to join it here in
                 --  the same commit, for the same reason from the other
                 --  direction: a message waiting for an answer holds the
                 --  seven-day lock, so a screen that ignored it would offer a
                 --  family the office could not actually write to. These two
                 --  queries have to agree or the screen is lying about what
                 --  the button will do.
                 'last_reminded_at', (select max(r.sent_at)
                                        from public.madrasah_fee_reminders r
                                       where r.household_id = h.id
                                         and r.outcome in ('sent', 'queued')),
                 --  What happened last time, so the screen can offer to try
                 --  again rather than leaving the office to guess why a
                 --  family it chased has heard nothing.
                 'last_reminder', (select jsonb_build_object(
                                            'at', r.sent_at, 'outcome', r.outcome,
                                            'error', r.error)
                                     from public.madrasah_fee_reminders r
                                    where r.household_id = h.id
                                      and r.outcome in ('sent', 'queued', 'failed')
                                    order by r.sent_at desc limit 1)
               ) as x
          from public.madrasah_households h
          left join (select household_id, sum(net_p)::bigint as total
                       from public.madrasah_charges group by household_id) c
                 on c.household_id = h.id
          left join (select household_id, sum(amount_p)::bigint as total,
                            max(received_on) as last_on
                       from public.madrasah_payments group by household_id) y
                 on y.household_id = h.id
         where h.masjid_id = v_masjid
           and (not p_only_owing or coalesce(c.total, 0) - coalesce(y.total, 0) > 0)
           and (v_like is null
                or h.name ilike v_like escape '\'
                or h.reference ilike v_like escape '\')
      ) s), '[]'::jsonb);
end $fn$;

-- ---------------------------------------------------------------------------
--  5. One family's statement — every charge and every payment
-- ---------------------------------------------------------------------------
create or replace function public.madrasah_household_statement(p_household uuid)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_ref    text;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may see a family''s account.'
      using errcode = '42501';
  end if;

  select reference into v_ref from public.madrasah_households
   where id = p_household and masjid_id = v_masjid;
  if v_ref is null then
    raise exception 'There is no such family at this masjid.' using errcode = 'no_data_found';
  end if;

  return jsonb_build_object(
    'household', public.madrasah_household_one(p_household),
    'charges', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id', c.id, 'charged_on', c.charged_on, 'kind', c.kind,
               'description', c.description, 'weeks', c.weeks, 'rate_p', c.rate_p,
               'gross_p', c.gross_p, 'discount_p', c.discount_p,
               'discount_note', c.discount_note, 'waived_p', c.waived_p,
               'waiver_note', c.waiver_note, 'net_p', c.net_p,
               'period', (select t.name from public.madrasah_fee_periods t where t.id = c.period_id))
             order by c.charged_on desc, c.created_at desc)
        from public.madrasah_charges c where c.household_id = p_household), '[]'::jsonb),
    'payments', coalesce((
      select jsonb_agg(jsonb_build_object(
               'id', y.id, 'received_on', y.received_on, 'kind', y.kind,
               'method', y.method, 'amount_p', y.amount_p,
               'bank_reference', y.bank_reference, 'note', y.note)
             order by y.received_on desc, y.created_at desc)
        from public.madrasah_payments y where y.household_id = p_household), '[]'::jsonb),
    'charged_p', coalesce((select sum(net_p) from public.madrasah_charges
                            where household_id = p_household), 0),
    'paid_p',    coalesce((select sum(amount_p) from public.madrasah_payments
                            where household_id = p_household), 0)
  );
end $fn$;

-- ---------------------------------------------------------------------------
--  6. Recording money
-- ---------------------------------------------------------------------------
create or replace function public.record_madrasah_payment(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_house  uuid := nullif(p->>'household_id', '')::uuid;
  v_kind   text := coalesce(nullif(btrim(coalesce(p->>'kind', '')), ''), 'payment');
  v_amt    integer;
  v_big    bigint;
  v_row    public.madrasah_payments%rowtype;
  v_ref    text;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may record money.'
      using errcode = '42501';
  end if;

  select reference into v_ref from public.madrasah_households
   where id = v_house and masjid_id = v_masjid;
  if v_ref is null then
    raise exception 'That payment has to belong to a family. Match it to one first.'
      using errcode = 'no_data_found';
  end if;

  --  Parsed as BIGINT and range-checked here, not cast straight to integer.
  --  `abs(-2147483648)` overflows, so the friendly message below was
  --  unreachable for exactly one input and the office would have seen
  --  "integer out of range" instead.
  begin
    v_big := (p->>'amount_p')::bigint;
  exception when others then
    raise exception 'That amount is not a number of pence.' using errcode = 'check_violation';
  end;
  if v_big is null or v_big = 0 then
    raise exception 'A payment of nothing is not a payment.' using errcode = 'check_violation';
  end if;
  if abs(v_big) > 10000000 then
    raise exception 'That is more than £100,000. Check the amount.'
      using errcode = 'check_violation';
  end if;
  v_amt := v_big::integer;

  --  THE SCREEN SENDS A POSITIVE NUMBER AND SAYS WHICH IT IS. The sign is
  --  applied here, once, so that a refund form which forgets the minus cannot
  --  record money coming IN. The table's own constraint then re-checks it.
  v_amt := case when v_kind = 'refund' then -abs(v_amt) else abs(v_amt) end;

  insert into public.madrasah_payments
    (masjid_id, household_id, kind, method, amount_p, received_on,
     bank_reference, note, recorded_by)
  values (v_masjid, v_house, v_kind,
          coalesce(nullif(btrim(coalesce(p->>'method', '')), ''), 'bank'),
          v_amt,
          coalesce(nullif(p->>'received_on', '')::date, current_date),
          nullif(btrim(coalesce(p->>'bank_reference', '')), ''),
          nullif(btrim(coalesce(p->>'note', '')), ''),
          auth.uid())
  returning * into v_row;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(),
          case when v_kind = 'refund' then 'madrasah_refund_recorded'
               else 'madrasah_payment_recorded' end,
          jsonb_build_object('id', v_row.id, 'household', v_ref,
                             'amount_p', v_row.amount_p, 'method', v_row.method));

  return jsonb_build_object('id', v_row.id, 'reference', v_ref);
end $fn$;

--  Removing one. Money entered twice is the commonest mistake on this screen
--  and there has to be a way back, but it is audited with the amount in it.
create or replace function public.delete_madrasah_payment(p_id uuid, p_why text default null)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_row    public.madrasah_payments%rowtype;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may remove a payment.'
      using errcode = '42501';
  end if;

  select * into v_row from public.madrasah_payments
   where id = p_id and masjid_id = v_masjid;
  if v_row.id is null then
    raise exception 'There is no such payment at this masjid.' using errcode = 'no_data_found';
  end if;

  delete from public.madrasah_payments where id = p_id and masjid_id = v_masjid;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(), 'madrasah_payment_removed',
          jsonb_build_object('id', p_id, 'household', v_row.household_id,
                             'amount_p', v_row.amount_p,
                             'received_on', v_row.received_on,
                             'why', nullif(btrim(coalesce(p_why, '')), '')));

  return jsonb_build_object('ok', true);
end $fn$;

-- ---------------------------------------------------------------------------
--  7. Discounts and waivers on a charge that already exists
--
--  A DISCOUNT AND A WAIVER ARE DIFFERENT THINGS AND THE MASJID SHOULD SEE
--  WHICH IS WHICH. A discount is the published rule applied — the second
--  child pays less because that is the policy. A waiver is a decision about
--  one family, usually hardship, usually taken by somebody who should be
--  accountable for it. Both reduce the bill; only one of them is a judgement.
--  Keeping them in separate columns is what lets the Annual report tell the
--  trustees "£1,240 of discount and £680 written off", which is a sentence
--  they can act on, instead of one number nobody can question.
-- ---------------------------------------------------------------------------
create or replace function public.adjust_madrasah_charge(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_id     uuid := nullif(p->>'id', '')::uuid;
  v_row    public.madrasah_charges%rowtype;
  v_disc   integer;
  v_waive  integer;
  v_dnote  text;
  v_wnote  text;
  v_net    integer;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may change a charge.'
      using errcode = '42501';
  end if;

  select * into v_row from public.madrasah_charges
   where id = v_id and masjid_id = v_masjid;
  if v_row.id is null then
    raise exception 'There is no such charge at this masjid.' using errcode = 'no_data_found';
  end if;

  v_disc  := greatest(coalesce(nullif(p->>'discount_p', '')::integer, v_row.discount_p), 0);
  v_waive := greatest(coalesce(nullif(p->>'waived_p',   '')::integer, v_row.waived_p),   0);

  --  AN ABSENT KEY MEANS "LEAVE IT ALONE". 058 set this rule for class lists
  --  and it matters more here. The amounts already followed it; the notes did
  --  not, so the Discounts screen — which sends only the waiver fields —
  --  silently wiped "Sibling discount" off every charge it touched, leaving
  --  an unexplained discount line in the annual report. That is precisely the
  --  thing the compulsory waiver reason exists to prevent, arrived at from
  --  the other direction.
  v_dnote := case when p ? 'discount_note'
                  then nullif(btrim(coalesce(p->>'discount_note', '')), '')
                  else v_row.discount_note end;
  v_wnote := case when p ? 'waiver_note'
                  then nullif(btrim(coalesce(p->>'waiver_note', '')), '')
                  else v_row.waiver_note end;

  if v_disc + v_waive > v_row.gross_p then
    raise exception 'That is more than the charge itself. The bill is %, and you have taken % off it.',
      '£' || to_char(v_row.gross_p / 100.0, 'FM999999990.00'),
      '£' || to_char((v_disc + v_waive) / 100.0, 'FM999999990.00')
      using errcode = 'check_violation';
  end if;

  --  A WRITE-OFF HAS TO SAY WHY. Not politeness: a waiver is the masjid
  --  giving away its own income, the trustees see the total in the annual
  --  report, and an unexplained line there is one somebody has to go and
  --  reconstruct from memory a year later.
  if v_waive > 0 and v_wnote is null then
    raise exception 'Say why the fee is being waived. It goes to the trustees in the annual report.'
      using errcode = 'check_violation';
  end if;

  update public.madrasah_charges
     set discount_p = v_disc, discount_note = v_dnote,
         waived_p = v_waive, waiver_note = v_wnote
   where id = v_id and masjid_id = v_masjid;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(), 'madrasah_charge_adjusted',
          jsonb_build_object('id', v_id, 'household', v_row.household_id,
                             'discount_p', v_disc, 'waived_p', v_waive,
                             'was_discount_p', v_row.discount_p,
                             'was_waived_p', v_row.waived_p));

  --  READ BACK, not recomputed. net_p is a generated column and this file's
  --  header says a second code path for it cannot exist — so this function
  --  should not be one, even though its arithmetic happens to agree today.
  select net_p into v_net from public.madrasah_charges where id = v_id;
  return jsonb_build_object('ok', true, 'net_p', v_net);
end $fn$;

create or replace function public.cancel_madrasah_charge(p_id uuid, p_why text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_row    public.madrasah_charges%rowtype;
  v_why    text := nullif(btrim(coalesce(p_why, '')), '');
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may cancel a charge.'
      using errcode = '42501';
  end if;
  if v_why is null then
    raise exception 'Say why the charge is being cancelled.' using errcode = 'check_violation';
  end if;

  select * into v_row from public.madrasah_charges
   where id = p_id and masjid_id = v_masjid;
  if v_row.id is null then
    raise exception 'There is no such charge at this masjid.' using errcode = 'no_data_found';
  end if;

  delete from public.madrasah_charges where id = p_id and masjid_id = v_masjid;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(), 'madrasah_charge_cancelled',
          jsonb_build_object('id', p_id, 'household', v_row.household_id,
                             'net_p', v_row.net_p, 'description', v_row.description,
                             'why', v_why));

  return jsonb_build_object('ok', true);
end $fn$;

--  Charging one family something one-off: an admission fee, or a balance
--  brought over from the old system.
create or replace function public.add_madrasah_charge(p jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $fn$
declare
  v_masjid uuid := public.current_masjid();
  v_house  uuid := nullif(p->>'household_id', '')::uuid;
  v_desc   text := btrim(coalesce(p->>'description', ''));
  v_gross  integer;
  v_pupil  uuid;
  v_row    public.madrasah_charges%rowtype;
begin
  if not public.verified_admin() then
    raise exception 'Only an administrator who has completed two-step may add a charge.'
      using errcode = '42501';
  end if;
  if not exists (select 1 from public.madrasah_households
                  where id = v_house and masjid_id = v_masjid) then
    raise exception 'There is no such family at this masjid.' using errcode = 'no_data_found';
  end if;
  if v_desc = '' then
    raise exception 'Say what the charge is for.' using errcode = 'check_violation';
  end if;

  begin
    v_gross := (p->>'gross_p')::integer;
  exception when others then
    raise exception 'That amount is not a number of pence.' using errcode = 'check_violation';
  end;
  if v_gross is null or v_gross <= 0 then
    raise exception 'A charge of nothing is not a charge.' using errcode = 'check_violation';
  end if;

  --  A PUPIL ID IS CHECKED AGAINST THIS MASJID AND THIS FAMILY. The foreign
  --  key only requires the child to exist somewhere, so without this a charge
  --  could be stamped with another masjid's pupil, or with a child from a
  --  different family — and madrasah_household_statement() would then show it
  --  on the wrong family's account.
  v_pupil := nullif(p->>'pupil_id', '')::uuid;
  if v_pupil is not null and not exists (
       select 1 from public.madrasah_pupils
        where id = v_pupil and masjid_id = v_masjid and household_id = v_house) then
    raise exception 'That child is not in this family.' using errcode = 'no_data_found';
  end if;

  insert into public.madrasah_charges
    (masjid_id, household_id, pupil_id, kind, description, gross_p, charged_on, created_by)
  values (v_masjid, v_house, v_pupil,
          coalesce(nullif(btrim(coalesce(p->>'kind', '')), ''), 'other'),
          v_desc, v_gross,
          coalesce(nullif(p->>'charged_on', '')::date, current_date), auth.uid())
  returning * into v_row;

  insert into public.admin_audit (masjid_id, actor, action, detail)
  values (v_masjid, auth.uid(), 'madrasah_charge_added',
          jsonb_build_object('id', v_row.id, 'household', v_house,
                             'gross_p', v_gross, 'kind', v_row.kind));

  return jsonb_build_object('id', v_row.id);
end $fn$;

grant execute on function public.raise_madrasah_charges(uuid)           to authenticated;
grant execute on function public.madrasah_fee_balances(boolean, text)   to authenticated;
grant execute on function public.madrasah_household_statement(uuid)     to authenticated;
grant execute on function public.record_madrasah_payment(jsonb)         to authenticated;
grant execute on function public.delete_madrasah_payment(uuid, text)    to authenticated;
grant execute on function public.adjust_madrasah_charge(jsonb)          to authenticated;
grant execute on function public.cancel_madrasah_charge(uuid, text)     to authenticated;
grant execute on function public.add_madrasah_charge(jsonb)             to authenticated;

commit;

-- ===========================================================================
--  CHECKS
-- ===========================================================================

--  #1  net_p is computed by the database, not by whoever is inserting.
do $c1$
declare v_gen text;
begin
  select attgenerated into v_gen from pg_attribute
   where attrelid = 'public.madrasah_charges'::regclass and attname = 'net_p';
  if coalesce(v_gen, '') <> 's' then
    raise exception 'CHECK 1 FAILED: madrasah_charges.net_p is not a stored generated column. A screen that forgets to subtract a waiver would report a different total from the annual report.';
  end if;
  raise notice 'CHECK 1 passed: what a family owes is computed by Postgres.';
end $c1$;

--  #2  A refund cannot be stored as money coming in, and a discount cannot
--      exceed the bill. Both asserted against the CONSTRAINTS, not through
--      the functions — going through the functions would be stopped by
--      verified_admin() first and the check would pass without ever
--      exercising the rule.
--
--      THE THROWAWAY MASJID IS WRITTEN OUT IN FULL, and it was not always.
--      The first version of this block inserted a masjid with a name and
--      nothing else, which is all the local harness needed. Production's
--      `masjids` has THREE not-null columns with no default — slug, name
--      and town — so the insert would have raised a not_null_violation and
--      taken the whole migration down with it, on a file that had passed
--      every time it was run. The harness was a smaller table wearing the
--      same name. A check is only as honest as the schema it ran against.
--
--      The slug is random because slug is unique, and a migration that can
--      only ever be applied once is a migration you cannot re-apply after
--      fixing something else in it. Everything here is deleted before the
--      block ends, and the cascade on masjid_id takes the household.
do $c2$
declare
  v_m uuid;
  v_h uuid;
  v_bad boolean;
begin
  insert into public.masjids (slug, name, town)
  values ('check2-' || replace(gen_random_uuid()::text, '-', ''),
          'CHECK-2 throwaway', 'Nowhere')
  returning id into v_m;
  insert into public.madrasah_households (masjid_id, reference, name)
  values (v_m, 'MF-9999', 'Check 2') returning id into v_h;

  v_bad := false;
  begin
    insert into public.madrasah_payments (masjid_id, household_id, kind, method, amount_p)
    values (v_m, v_h, 'refund', 'bank', 5000);
    v_bad := true;
  exception when check_violation then null;
  end;
  if v_bad then
    raise exception 'CHECK 2 FAILED: a refund was stored as a positive amount. It would have increased what the family had paid.';
  end if;

  v_bad := false;
  begin
    insert into public.madrasah_charges
      (masjid_id, household_id, description, gross_p, discount_p, waived_p)
    values (v_m, v_h, 'Check 2', 1000, 600, 600);
    v_bad := true;
  exception when check_violation then null;
  end;
  if v_bad then
    raise exception 'CHECK 2 FAILED: relief of £12 was allowed against a bill of £10. The family would have gone into credit and dropped off the Outstanding screen.';
  end if;

  --  And the honest half: a correct row must still go in, or the two
  --  rejections above prove only that the table refuses everything.
  insert into public.madrasah_payments (masjid_id, household_id, kind, method, amount_p)
  values (v_m, v_h, 'refund', 'bank', -5000);
  insert into public.madrasah_charges
    (masjid_id, household_id, description, gross_p, discount_p, waived_p)
  values (v_m, v_h, 'Check 2', 1000, 250, 250);

  delete from public.madrasah_charges  where masjid_id = v_m;
  delete from public.madrasah_payments where masjid_id = v_m;
  delete from public.masjids           where id = v_m;
  raise notice 'CHECK 2 passed: the sign of a refund and the size of a discount are enforced by the table.';
end $c2$;

--  #3  Running the generator twice does not charge twice.
--      Somebody will press it twice. The index is what makes that harmless.
do $c3$
declare v_ok boolean;
begin
  select exists (
    select 1 from pg_indexes
     where schemaname = 'public'
       and indexname = 'madrasah_charge_one_per_pupil_per_term_idx'
       and indexdef ilike '%UNIQUE%')
    into v_ok;
  if not v_ok then
    raise exception 'CHECK 3 FAILED: nothing stops a term being charged twice.';
  end if;
  raise notice 'CHECK 3 passed: raising charges for a term is safe to press twice.';
end $c3$;

--  #4  Deleting a pupil, or a family, must never delete the money record.
--      058's rule about safeguarding, applied to the charity's own accounts,
--      which are on a six-year clock and not the pupil's three-year one.
do $c4$
declare v_rule text; v_bad text := '';
begin
  select confdeltype::text into v_rule from pg_constraint
   where conrelid = 'public.madrasah_charges'::regclass and contype = 'f'
     and confrelid = 'public.madrasah_pupils'::regclass;
  if coalesce(v_rule, '') <> 'n' then
    v_bad := v_bad || 'charges->pupils is not SET NULL. ';
  end if;

  foreach v_rule in array array[
    (select confdeltype::text from pg_constraint
      where conrelid = 'public.madrasah_charges'::regclass and contype='f'
        and confrelid = 'public.madrasah_households'::regclass),
    (select confdeltype::text from pg_constraint
      where conrelid = 'public.madrasah_payments'::regclass and contype='f'
        and confrelid = 'public.madrasah_households'::regclass)] loop
    if coalesce(v_rule, '') <> 'r' then
      v_bad := v_bad || 'a money table does not RESTRICT deletion of the family it belongs to. ';
    end if;
  end loop;

  if v_bad <> '' then
    raise exception 'CHECK 4 FAILED: %The three-year pupil purge would take the charity''s financial records with it.', v_bad;
  end if;
  raise notice 'CHECK 4 passed: deleting people never deletes the money record.';
end $c4$;

--  #5  Every function here is administrators only. Line-based — 065.
do $c5$
declare v_fn text; v_def text; v_line text; v_found boolean;
begin
  foreach v_fn in array array['raise_madrasah_charges', 'madrasah_fee_balances',
                              'madrasah_household_statement', 'record_madrasah_payment',
                              'delete_madrasah_payment', 'adjust_madrasah_charge',
                              'cancel_madrasah_charge', 'add_madrasah_charge'] loop
    select pg_get_functiondef(p.oid) into v_def
      from pg_proc p join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = v_fn limit 1;
    if v_def is null then
      raise exception 'CHECK 5 FAILED: public.%() does not exist.', v_fn;
    end if;
    v_found := false;
    foreach v_line in array string_to_array(v_def, E'\n') loop
      if btrim(v_line) not like '--%' and v_line like '%public.verified_admin()%' then
        v_found := true; exit;
      end if;
    end loop;
    if not v_found then
      raise exception 'CHECK 5 FAILED: public.%() never calls public.verified_admin() in live code. A teacher could read what every family at the masjid owes.', v_fn;
    end if;
  end loop;
  raise notice 'CHECK 5 passed: the whole ledger is administrators only.';
end $c5$;

-- ===========================================================================
--  AFTER APPLYING THIS FILE — re-run db/011_require_two_step.sql.
-- ===========================================================================
