#!/usr/bin/env python3
"""Write the seven Fees screens from one shell.

WHY A GENERATOR AND NOT SEVEN HAND-WRITTEN FILES
------------------------------------------------
Every portal screen carries the whole sign-in shell — loading, sign in, the
two-step challenge, the enrolment QR — copied inline. That is the house
pattern and it is not wrong: each screen is standalone, with no build step
between the file and the browser.

At seven screens in one section it stops being copying and starts being
drift. The Fees screens are the ones that decide who may see what a family
owes, and seven hand-copied sign-in shells is seven places for that to be
subtly different. So the shell is taken from portal/classes/index.html and
the seven files are written from it.

This is a GENERATOR, not a build step. It runs when somebody adds a screen
or changes the shell; the files it writes are committed and served exactly
as they are, and nothing at run time depends on this script existing. That
is the difference from build.py, which must be run before every push.

    python3 tools/build_fees_screens.py

It refuses to run if the shell it copies from has moved, rather than writing
seven broken screens.
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHELL = os.path.join(ROOT, "portal", "classes", "index.html")

PATH_NOTE = """<!-- ===========================================================================
     THIS SCREEN IS %d FOLDERS BELOW THE WEB ROOT.

     So every path to a shared file is "%s", the madrasah portal above is
     "%s", and gate.js and fees.css live in the Fees folder beside it.

     Worth stating because getting it wrong FAILS SILENTLY. A missing
     stylesheet does not throw — it renders an unstyled page that reads as a
     markup bug. A missing shell.js simply never draws the rail, which reads
     as a screen that was built without one.

     THIS FILE IS GENERATED by tools/build_fees_screens.py. Editing it by hand
     works until somebody runs that script again. Change the generator.
     =========================================================================== -->"""

PANEL_NOTE = """<!-- The Fees screen itself. Hidden unless the signed-in person is an
           administrator. The database refuses every one of these calls to
           anybody else regardless, and the rail marks the whole section
           ADMIN — but there is no reason to show a teacher a panel full of
           error messages and let them think it is broken. -->"""

SECTION_LEAD = (
    "Fees are collected by bank transfer, by card and in the office. "
    "Everything that arrives is recorded in one place so that what a family "
    "owes is a single number, and the same number wherever it is read."
)


def read_shell():
    if not os.path.exists(SHELL):
        sys.exit("The shell screen %s is missing. Nothing written." % SHELL)
    src = open(SHELL, encoding="utf-8").read()

    for marker in ('<style>', '<body>', 'id="cl-panel"', 'id="app-signout"'):
        if marker not in src:
            sys.exit("The shell has changed — %s is gone. Nothing written, so "
                     "that seven screens are not written wrongly." % marker)

    i = src.index("<style>")
    head = src[:i]

    b = src.index("<body>")
    sec = src.index('<section class="bk" id="cl-panel" hidden>')
    shell_top = src[b:sec]

    tail_at = src.rindex("</section>")
    tail = src[tail_at + len("</section>"):]
    return head, shell_top, tail


def rel(depth):
    """How many ../ a file at this depth needs to reach the web root."""
    return "../" * depth


# ---------------------------------------------------------------------------
#  The seven screens. `key` must match the row in portal/nav.js, or the rail
#  highlights nothing — admin_shell_test.py checks that they agree.
# ---------------------------------------------------------------------------
SCREENS = []


def screen(key, folder, depth, title, h1, lead, body):
    SCREENS.append(dict(key=key, folder=folder, depth=depth, title=title,
                        h1=h1, lead=lead, body=body))


# --- 1. the landing screen -------------------------------------------------
screen(
    "md-fees", "portal/fees", 2, "Fees", "Fees",
    "What has been charged, what has come in, and what is still owed. "
    "Every figure here is worked out from the same rows the rest of the "
    "section shows, so nothing on this page can disagree with the screen "
    "it links to.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>Where the money is</h2>
            <p>%s</p>
          </div>
          <div class="fx-head-a">
            <a class="btn btn-gold"  href="transfers/">Record money in</a>
            <a class="btn btn-ghost" href="owing/">Chase what is owed</a>
          </div>
        </div>

        <div class="err" id="fx-error" hidden></div>

        <!-- Shown until the section can actually take money. -->
        <div class="fx-setup" id="fx-setup" hidden>
          <h3>Before fees can be collected</h3>
          <p class="fx-sub" id="fx-setup-lead"></p>
          <ol id="fx-setup-list"></ol>
        </div>

        <div class="fx-figs" id="fx-figs"></div>

        <div class="fx-bk">
          <h3>Money arriving</h3>
          <p class="fx-sub">The last five receipts, whichever way they came in.</p>
          <div id="fx-recent"></div>
        </div>

        <div class="fx-bk">
          <h3>Worth a look</h3>
          <p class="fx-sub">Things that will quietly cost the madrasah money
             if nobody deals with them.</p>
          <div id="fx-attention"></div>
        </div>
""" % SECTION_LEAD)


# --- 1b. families -----------------------------------------------------------
screen(
    "md-families", "portal/fees/families", 3, "Families", "Families",
    "Who pays, who to write to, and which children belong to them. Nothing "
    "in this section works until the children are in families \u2014 543 were "
    "imported from a class list that has no family column in it, so on day "
    "one every one of them is unhoused.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>Who pays</h2>
            <p>A family is the unit everything else here is built on: one bill
               covers three children, one transfer arrives for all of them, and
               the sibling discount is a statement about a family rather than a
               child. Each one gets a reference the parents quote when they
               pay.</p>
          </div>
          <div class="fx-head-a">
            <button type="button" class="btn btn-gold" id="fm-new">Add a family</button>
          </div>
        </div>

        <div class="err"   id="fx-error" hidden></div>
        <div class="fx-ok" id="fx-ok" hidden></div>

        <div class="fx-figs" id="fm-figs"></div>

        <div class="fx-bk" id="fm-editor-bk" hidden>
          <h3 id="fm-editor-t">A family</h3>
          <div id="fm-editor"></div>
        </div>

        <div class="fx-bk">
          <h3>Children with no family</h3>
          <p class="fx-sub">These children are not billed for. When charges are
             raised they are skipped, and the screen says how many &mdash; but
             skipped means nobody is asked to pay for them.</p>
          <div class="fx-bar">
            <input type="search" id="fm-psearch" placeholder="Find a child by name">
            <span class="fx-count" id="fm-pcount"></span>
          </div>
          <div id="fm-unhoused"></div>
        </div>

        <div class="fx-bk">
          <h3>Families</h3>
          <div class="fx-bar">
            <input type="search" id="fm-search" placeholder="Family name or MF- reference">
            <span class="fx-count" id="fm-count"></span>
          </div>
          <div id="fm-list"></div>
        </div>
""")


# --- 2. bank transfers -----------------------------------------------------
screen(
    "md-transfers", "portal/fees/transfers", 3, "Bank transfers",
    "Bank transfers",
    "Where money is recorded. Most madrasah fees arrive as a bank transfer "
    "quoting a family reference; card payments and cash are entered here too, "
    "so that there is one list of everything that has come in rather than "
    "three that have to be added up.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>Record money in</h2>
            <p>Find the family, type what arrived. A card payment taken through
               Stripe is entered here as well &mdash; it is recorded by a person
               who has seen it, not posted automatically, because a reference
               typed wrongly by a parent would credit the wrong family and
               nothing on any screen would say so.</p>
          </div>
        </div>

        <div class="err" id="fx-error" hidden></div>
        <div class="fx-ok"  id="fx-ok" hidden></div>

        <div class="fx-bk">
          <h3>A receipt</h3>
          <p class="fx-sub">Search by the reference on the statement, or by the
             family's name if a parent is on the telephone.</p>

          <div class="fx-form">
            <label class="fx-fld wide fx-picker">
              <span>Family</span>
              <input type="text" id="tr-family" autocomplete="off"
                     placeholder="MF-0148, or a surname">
              <div class="fx-results" id="tr-results" hidden></div>
              <span class="hint" id="tr-balance">&nbsp;</span>
            </label>

            <label class="fx-fld">
              <span>Amount</span>
              <input type="text" id="tr-amount" inputmode="decimal" placeholder="£0.00">
            </label>

            <label class="fx-fld">
              <span>Date received</span>
              <input type="date" id="tr-date">
            </label>

            <label class="fx-fld">
              <span>How it arrived</span>
              <select id="tr-method">
                <option value="bank">Bank transfer</option>
                <option value="card">Card (Stripe)</option>
                <option value="cash">Cash in the office</option>
                <option value="other">Something else</option>
              </select>
            </label>

            <label class="fx-fld">
              <span>Reference on the statement</span>
              <input type="text" id="tr-ref" maxlength="60"
                     placeholder="exactly as the bank shows it">
              <span class="hint">Type what the bank actually says, even if it
                    is wrong. In six months that string is the only way back
                    to this row.</span>
            </label>

            <label class="fx-fld wide">
              <span>Note (optional)</span>
              <input type="text" id="tr-note" maxlength="300">
            </label>
          </div>

          <div class="fx-acts">
            <button type="button" class="btn btn-gold"  id="tr-save">Record it</button>
            <button type="button" class="btn btn-ghost" id="tr-clear">Clear</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>Recorded recently</h3>
          <p class="fx-sub">The last fifty receipts. Money entered twice is the
             commonest mistake on this screen, so there is a way back &mdash; and
             it is written into the audit.</p>
          <div class="fx-bar">
            <input type="search" id="tr-search" placeholder="Family or reference">
            <span class="fx-count" id="tr-count"></span>
          </div>
          <div id="tr-list"></div>
        </div>
""")


# --- 3. outstanding & reminders --------------------------------------------
screen(
    "md-outstanding", "portal/fees/owing", 3, "Outstanding &amp; reminders",
    "Outstanding &amp; reminders",
    "Every family with something still to pay, largest first. Tick the ones "
    "to write to and press send; the email says what is owed and how to pay "
    "it, and never names a child.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>What is still owed</h2>
            <p>A reminder goes to one parent per family &mdash; the one marked as
               the contact &mdash; and only if that family still owes something at
               the moment you press send. The same family is not written to
               twice in seven days.</p>
          </div>
          <div class="fx-head-a">
            <!-- Hidden until there is something to retry, and in the HEADER
                 rather than in the selection bar. It was in the bar, which is
                 itself hidden until a family is ticked — so the one control
                 for "these did not go" was invisible in exactly the state
                 where somebody needs it. -->
            <button type="button" class="btn btn-gold" id="ow-again" hidden>
              Try the failed ones again</button>
            <button type="button" class="btn btn-ghost" id="ow-csv">Download for Excel</button>
          </div>
        </div>

        <div class="err"   id="fx-error" hidden></div>
        <div class="fx-ok" id="fx-ok" hidden></div>

        <div class="fx-figs" id="ow-figs"></div>

        <div class="fx-bk">
          <div class="fx-bar">
            <input type="search" id="ow-search" placeholder="Family or reference">
            <label class="fx-fld" style="flex-direction:row;align-items:center;gap:8px">
              <input type="checkbox" id="ow-onlyemail" style="width:18px;height:18px">
              <span style="text-transform:none;letter-spacing:0;font-size:.88rem">
                Only families we can email</span>
            </label>
            <span class="fx-count" id="ow-count"></span>
          </div>

          <div class="fx-acts" id="ow-bar" hidden>
            <button type="button" class="btn btn-gold" id="ow-send">Send reminders</button>
            <button type="button" class="btn btn-ghost" id="ow-none">Clear selection</button>
            <span class="fx-note" id="ow-picked" style="margin:0"></span>
          </div>

          <div class="fx-confirm" id="ow-confirm" hidden>
            <p id="ow-confirm-t"></p>
            <div class="fx-acts">
              <button type="button" class="btn btn-gold"  id="ow-yes">Yes, send them</button>
              <button type="button" class="btn btn-ghost" id="ow-no">No</button>
            </div>
          </div>

          <div id="ow-list"></div>
        </div>

        <div class="fx-bk" id="ow-result-bk" hidden>
          <h3>What happened</h3>
          <p class="fx-sub">Including the ones nothing was sent to, and why.</p>
          <div id="ow-result"></div>
        </div>
""")


# --- 4. discounts & waivers ------------------------------------------------
screen(
    "md-discounts", "portal/fees/discounts", 3, "Discounts &amp; waivers",
    "Discounts &amp; waivers",
    "The sibling discount, and fees the masjid has decided not to collect. "
    "A discount is the published rule applied. A waiver is a decision about "
    "one family, and the trustees see the total.",
    """
        <div class="err"   id="fx-error" hidden></div>
        <div class="fx-ok" id="fx-ok" hidden></div>

        <div class="fx-bk">
          <h3>The sibling discount</h3>
          <p class="fx-sub">How much less each additional child in a family
             pays. The child who has been at the madrasah longest is counted
             first; a child who has left stops counting, so a family of three
             whose eldest left in July is billed as a family of two.</p>

          <div id="sd-rules"></div>

          <div class="fx-acts">
            <button type="button" class="btn btn-ghost" id="sd-add">Add a position</button>
            <button type="button" class="btn btn-gold"  id="sd-save">Save the rule</button>
          </div>
          <p class="fx-note" id="sd-example"></p>
          <p class="fx-note"><strong>Changing this does not change bills that
             have already been raised.</strong> It applies the next time charges
             are raised for a term.</p>
        </div>

        <div class="fx-bk">
          <h3>Waive a fee</h3>
          <p class="fx-sub">Find the family, open the charge, and say what is
             being written off and why. The reason is not optional &mdash; it goes
             to the trustees in the annual report, and an unexplained line
             there is one somebody has to reconstruct from memory a year on.</p>

          <div class="fx-form">
            <label class="fx-fld wide fx-picker">
              <span>Family</span>
              <input type="text" id="wv-family" autocomplete="off"
                     placeholder="MF-0148, or a surname">
              <div class="fx-results" id="wv-results" hidden></div>
            </label>
          </div>
          <div id="wv-charges"></div>
        </div>

        <div class="fx-bk">
          <h3>Written off so far</h3>
          <p class="fx-sub">Everything currently carrying a waiver, with the
             reason given.</p>
          <div id="wv-list"></div>
        </div>
""")


# --- 5. refunds ------------------------------------------------------------
screen(
    "md-refunds", "portal/fees/refunds", 3, "Refunds", "Refunds",
    "Money going back to a family — usually because they left part-way "
    "through a term they had already paid for. A refund is recorded against "
    "the family like any other movement, with a minus sign, so the balance "
    "arithmetic never needs a special case.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>Give money back</h2>
            <p>A family in credit has paid more than they have been charged.
               That is where a refund normally belongs, and those families are
               listed below so nobody has to go looking.</p>
          </div>
        </div>

        <div class="err"   id="fx-error" hidden></div>
        <div class="fx-ok" id="fx-ok" hidden></div>

        <div class="fx-bk">
          <h3>Families in credit</h3>
          <p class="fx-sub">Paid more than they owe. Most refunds start here.</p>
          <div id="rf-credit"></div>
        </div>

        <div class="fx-bk">
          <h3>Record a refund</h3>
          <div class="fx-form">
            <label class="fx-fld wide fx-picker">
              <span>Family</span>
              <input type="text" id="rf-family" autocomplete="off"
                     placeholder="MF-0148, or a surname">
              <div class="fx-results" id="rf-results" hidden></div>
              <span class="hint" id="rf-balance">&nbsp;</span>
            </label>

            <label class="fx-fld">
              <span>Amount to refund</span>
              <input type="text" id="rf-amount" inputmode="decimal" placeholder="£0.00">
            </label>

            <label class="fx-fld">
              <span>Date</span>
              <input type="date" id="rf-date">
            </label>

            <label class="fx-fld">
              <span>How it is going back</span>
              <select id="rf-method">
                <option value="bank">Bank transfer</option>
                <option value="cash">Cash in the office</option>
                <option value="card">Card (refunded in Stripe)</option>
                <option value="other">Something else</option>
              </select>
            </label>

            <label class="fx-fld wide">
              <span>Why</span>
              <input type="text" id="rf-note" maxlength="300"
                     placeholder="Left in November having paid the term">
            </label>
          </div>

          <div class="fx-confirm" id="rf-confirm" hidden>
            <p id="rf-confirm-t"></p>
            <div class="fx-acts">
              <button type="button" class="btn btn-gold"  id="rf-yes">Yes, record it</button>
              <button type="button" class="btn btn-ghost" id="rf-no">No</button>
            </div>
          </div>

          <div class="fx-acts">
            <button type="button" class="btn btn-gold"  id="rf-save">Record the refund</button>
            <button type="button" class="btn btn-ghost" id="rf-clear">Clear</button>
          </div>
          <p class="fx-note">This records that the masjid has refunded the
             money. It does not move any money by itself &mdash; make the transfer
             or the Stripe refund first, then record it here.</p>
        </div>

        <div class="fx-bk">
          <h3>Refunded so far</h3>
          <div id="rf-list"></div>
        </div>
""")


# --- 6. what things cost ---------------------------------------------------
screen(
    "md-structure", "portal/fees/structure", 3, "What things cost",
    "What things cost",
    "The rate card, the terms it is charged over, and where parents send the "
    "money. This is the screen that lets the office change a price without "
    "anybody editing the website.",
    """
        <div class="err"   id="fx-error" hidden></div>
        <div class="fx-ok" id="fx-ok" hidden></div>

        <div class="fx-setup" id="st-unconfirmed" hidden>
          <h3>Nobody has confirmed these figures</h3>
          <p class="fx-sub">The rates below were taken from the admissions page
             on the website &mdash; £10 a week, £14 for Hifz, £20 to join. The
             office has never confirmed that they are still right, and the
             question has been open since the admissions work in September.
             Until somebody presses the button, every screen that uses these
             figures says they are unconfirmed.</p>
          <div class="fx-acts">
            <button type="button" class="btn btn-gold" id="st-confirm">
              These are the right figures</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>The rate card</h3>
          <p class="fx-sub">What a week costs. The default is what a child is
             charged unless somebody has put them on a different rate.</p>
          <div id="st-rates"></div>
          <div class="fx-acts">
            <button type="button" class="btn btn-ghost" id="st-rate-add">Add a rate</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>Terms</h3>
          <p class="fx-sub">A term is a name, two dates and the number of weeks
             that are actually charged &mdash; which the office decides, because
             madrasah terms do not match school terms and they break for
             Ramadan and Eid. A bill is that number of weeks times the rate.</p>
          <div id="st-periods"></div>
          <div class="fx-acts">
            <button type="button" class="btn btn-ghost" id="st-period-add">Add a term</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>Where parents send the money</h3>
          <p class="fx-sub">Shown to parents in every reminder. Changing any of
             these is recorded with your name against it, and the screen keeps
             showing who changed them last &mdash; a quiet change to a sort code
             is the dangerous kind.</p>
          <p class="fx-note" id="st-bank-when"></p>

          <div class="fx-form">
            <label class="fx-fld">
              <span>Bank</span>
              <input type="text" id="st-bank-name" maxlength="60" placeholder="HSBC">
            </label>
            <label class="fx-fld">
              <span>Account name</span>
              <input type="text" id="st-bank-acname" maxlength="80"
                     placeholder="Bolton Central Islamic Society">
            </label>
            <label class="fx-fld">
              <span>Sort code</span>
              <input type="text" id="st-bank-sort" maxlength="8" placeholder="00-00-00">
            </label>
            <label class="fx-fld">
              <span>Account number</span>
              <input type="text" id="st-bank-no" maxlength="8" inputmode="numeric"
                     placeholder="00000000">
            </label>
            <label class="fx-fld wide" id="st-bank-again-w" hidden>
              <span>Type the account number again</span>
              <input type="text" id="st-bank-again" maxlength="8" inputmode="numeric">
              <span class="hint">Changing the account fees are paid into is the
                    single most valuable thing somebody could do with a stolen
                    administrator account. Typing it twice is the friction that
                    makes it deliberate.</span>
            </label>
          </div>
          <div class="fx-acts">
            <button type="button" class="btn btn-gold" id="st-bank-save">Save bank details</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>Paying by card</h3>
          <p class="fx-sub">A Stripe payment link, if the masjid has one. Leave
             it empty and reminders simply tell parents to pay by bank transfer
             or in the office.</p>
          <div class="fx-form">
            <label class="fx-fld wide">
              <span>Stripe payment link</span>
              <input type="text" id="st-card" maxlength="200"
                     placeholder="https://buy.stripe.com/...">
              <span class="hint">It has to be a link from the masjid's own
                    Stripe account. Anything else is refused &mdash; by the
                    database, not just by this box.</span>
            </label>
          </div>
          <div class="fx-acts">
            <button type="button" class="btn btn-gold" id="st-card-save">Save the link</button>
          </div>
        </div>

        <div class="fx-bk">
          <h3>What a reminder says</h3>
          <p class="fx-sub">Leave these empty to use the standard wording. The
             amount, the family reference and how to pay are added
             automatically and cannot be removed.</p>
          <div class="fx-form">
            <label class="fx-fld wide">
              <span>Subject</span>
              <input type="text" id="st-rem-sub" maxlength="120"
                     placeholder="Madrasah fees — Taiyabah Masjid">
            </label>
            <label class="fx-fld wide">
              <span>Opening line</span>
              <textarea id="st-rem-body" maxlength="600"
                        placeholder="Assalamu alaikum. This is a reminder about the madrasah fees for your family."></textarea>
            </label>
          </div>
          <div class="fx-acts">
            <button type="button" class="btn btn-gold" id="st-rem-save">Save the wording</button>
          </div>
        </div>
""")


# --- 7. annual report ------------------------------------------------------
screen(
    "md-fees-year", "portal/fees/annual", 3, "Annual report", "Annual report",
    "What was charged, what came in, and what was given away — for the "
    "trustees, and for the charity's annual return.",
    """
        <div class="fx-head">
          <div class="fx-head-t">
            <h2>The year in figures</h2>
            <p>Charges are counted on the day they were raised and payments on
               the day the money arrived, so the two will not match. That is
               normal, and saying so here saves a treasurer an evening.</p>
          </div>
          <div class="fx-head-a">
            <button type="button" class="btn btn-ghost" id="an-csv">Download for Excel</button>
            <button type="button" class="btn btn-ghost" id="an-print">Print</button>
          </div>
        </div>

        <div class="err" id="fx-error" hidden></div>

        <div class="fx-bar">
          <label class="fx-fld" style="flex-direction:row;align-items:center;gap:8px">
            <span style="text-transform:none;letter-spacing:0">From</span>
            <input type="date" id="an-from">
          </label>
          <label class="fx-fld" style="flex-direction:row;align-items:center;gap:8px">
            <span style="text-transform:none;letter-spacing:0">To</span>
            <input type="date" id="an-to">
          </label>
          <button type="button" class="btn btn-ghost" id="an-go">Show it</button>
          <span class="fx-count" id="an-when"></span>
        </div>

        <div class="fx-figs" id="an-figs"></div>

        <div class="fx-bk">
          <h3>By term</h3>
          <div id="an-periods"></div>
        </div>

        <div class="fx-bk">
          <h3>How the money came in</h3>
          <div id="an-methods"></div>
        </div>

        <div class="fx-bk">
          <h3>Fees written off</h3>
          <p class="fx-sub">Every waiver in the period, with the reason given
             at the time. This is the part of the report the trustees are most
             likely to ask about.</p>
          <div id="an-waivers"></div>
        </div>
""")


def build():
    head, shell_top, tail = read_shell()
    written = []

    for s in SCREENS:
        r = rel(s["depth"])
        gate = "gate.js" if s["depth"] == 2 else "../gate.js"
        css = "fees.css" if s["depth"] == 2 else "../fees.css"
        nav = r[:-3] + "nav.js" if s["depth"] > 2 else "../nav.js"

        # head: retitle, repoint, and swap the inline <style> for the shared
        # stylesheet. The token block is identical on every screen, so seven
        # copies of it would be seven chances for the plum to drift.
        h = head
        h = re.sub(r"<title>.*?</title>",
                   "<title>%s &mdash; Fees &mdash; Madrasah &mdash; Taiyabah Masjid</title>"
                   % s["title"], h, flags=re.S)
        # The shell's path comment describes /portal/staff/. Left as it is,
        # every generated screen would carry a confident statement about its
        # own depth that is wrong for six of the seven — which is worse than
        # no comment, because somebody fixing a path would trust it.
        h = re.sub(r"<!-- =+\n     THIS SCREEN IS TWO FOLDERS DOWN.*?-->",
                   PATH_NOTE % (s["depth"], "../" * s["depth"],
                                "../" if s["depth"] == 2 else "../../"),
                   h, flags=re.S)
        h = h.replace("../../fonts/", r + "fonts/")
        h = h.replace("../../admin/", r + "admin/")
        h = h.replace('src="../nav.js"', 'src="%s"' % nav)
        #  Furniture first, section second. admin/screen.css carries the
        #  tokens, the sign-in panel, the buttons and the fields; fees.css
        #  carries what is about money. A section sheet may override
        #  furniture, so it has to come after it.
        h = h.rstrip() + ('\n<link rel="stylesheet" href="%sadmin/screen.css">'
                          '\n<link rel="stylesheet" href="%s">\n</head>\n'
                          % (r, css))
        h = h.replace("</head>\n<link", "<link")          # keep one </head>

        top = shell_top
        top = re.sub(r"<h1>.*?</h1>", "<h1>%s</h1>" % s["h1"], top, flags=re.S)
        top = re.sub(r"<h1>%s</h1>\s*\n\s*<p>.*?</p>" % re.escape(s["h1"]),
                     "<h1>%s</h1>\n      <p>%s</p>" % (s["h1"], s["lead"]),
                     top, flags=re.S)
        back = "../" if s["depth"] == 2 else "../"
        top = re.sub(r'<a class="back" href="[^"]*">.*?</a>',
                     '<a class="back" href="%s">&larr; Back to %s</a>'
                     % (back, "the madrasah portal" if s["depth"] == 2 else "Fees"),
                     top, flags=re.S)
        top = top.replace('<section class="bk" id="cl-panel" hidden>', "")
        top = re.sub(r"<!-- The staff themselves\..*?-->", PANEL_NOTE, top, flags=re.S)

        t = tail
        t = t.replace("../../admin/", r + "admin/")
        t = t.replace('<script src="app.js"></script>',
                      '<script src="%s"></script>\n<script src="app.js"></script>' % gate)

        html = (h + top
                + '      <section class="bk" id="fx-panel" hidden>\n'
                + s["body"]
                + "      </section>\n" + t)

        folder = os.path.join(ROOT, s["folder"])
        os.makedirs(folder, exist_ok=True)
        open(os.path.join(folder, "index.html"), "w", encoding="utf-8").write(html)

        # config.js is byte-for-byte identical in every portal screen.
        src_cfg = os.path.join(ROOT, "portal", "classes", "config.js")
        open(os.path.join(folder, "config.js"), "w", encoding="utf-8").write(
            open(src_cfg, encoding="utf-8").read())

        written.append((s["folder"], len(html)))

    for folder, n in written:
        print("  %-28s %6d bytes" % (folder + "/index.html", n))
    print("\n%d screens written." % len(written))


if __name__ == "__main__":
    build()
