#!/usr/bin/env python3
"""Write portal/pupils/index.html, app.js and config.js.

The mechanism lives in tools/screen_builder.py, which is shared by every staff
screen; this file is only the description of THIS screen. See that module for
why the furniture is generated rather than copied, and why the JavaScript is
parsed before anything is written.

This screen was generated by its own copy of the builder until 27 September.
The copy was retired only after screen_builder.py was shown to reproduce both
of its output files byte for byte:

    python3 tools/screen_builder.py --verify-pupils

That check remains, and it is the reason the shared builder can be trusted with
a screen that has 157 checks against it.

NOT part of `python3 build.py`. Run it by hand; what it writes is committed
and served exactly as it lands.

    python3 tools/build_pupils_screen.py
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from screen_builder import Screen, build, ROOT  # noqa: E402

LEAD = ("Every child on the roll, the class they are in, who teaches them and "
        "who to ring. The list says whether a child has a medical note; the "
        "record says what it is, and writes down who opened it.")

SCREEN = Screen(
    name="Pupils",
    nav_key="md-pupils",
    folder="pupils",
    lead=LEAD,
    panel_id="pu-panel",
    module="pupils_module.js",
    var_name="pupils",
    css="pupils.css",
    body=open(os.path.join(ROOT, "tools", "_pupils_body.html"),
              encoding="utf-8").read(),
)

if __name__ == "__main__":
    build(SCREEN)
